accountapp/urls.py
from django.urls import path
from accountapp.views import AccountCreateView,AccountDetailView,AccountUpdateView,AccountDeleteView
from django.contrib.auth.views import LoginView,LogoutView

app_name = "accountapp"

urlpatterns = [
    
    #sign up
    path('create/', AccountCreateView.as_view()  , name='create'),
    #login
    #loginview는 template을 정해줘야 함
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html')  , name='login'),
    #logout
    path('logout/', LogoutView.as_view()  , name='logout'),
    #detail
    path('detail/<int:pk>', AccountDetailView.as_view()  , name='detail'),
    #update
    path('update/<int:pk>', AccountUpdateView.as_view()  , name='update'),
    #delete
    path('delete/<int:pk>', AccountDeleteView.as_view()  , name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from articleapp.views import ArticleCreateView,ArticleDetailView, ArticleListView,ArticleUpdateView,ArticleDeleteView

app_name = 'articleapp'

urlpatterns = [
    #list
    path('list/', ArticleListView.as_view(), name='list'),
    #create
    path('create/', ArticleCreateView.as_view(), name='create'),
    #detail
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    #update
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    #delete
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(), name='home'),
    #admin page
    path('admin/', admin.site.urls),
    #accountapp
    path('accounts/', include('accountapp.urls')),
    #profileapp
    path('profiles/', include('profileapp.urls')),
    #articlesapp
    path('articles/', include('articleapp.urls')),
    #commentapp
    path('comments/', include('commentapp.urls')),
    #projectapp
    path('projects/',include('projectapp.urls')),
    #subscribeapp
    path('subscribe/',include('subscribeapp.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path,include
from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView


app_name ='projectapp'

urlpatterns = [
    path('list/',ProjectListView.as_view(), name='list'),
    path('create/',ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path,include
from subscribeapp.views import SubscriptionView,SubscriptionListView


app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}

    <hr>

    {% block content %}
    
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="pragmatic_footer">

    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스소개</span> |
        
    </div>

    <div style="margin-top: 1rem;">
        <h6 class="pragmatic_footer_log">Pragmatic</h6>
    </div>


</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>project</title>
    <!-- bootstrap link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- google font link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gugi&family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <!-- google material icons -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <!-- default css link  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
</head>

templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 class="pragmatic_logo">pragmatic</h1>
    </div>

    <div class="pragmatic_header_navbar">
        <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
            <span>Projects</span>
        </a>

        <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
            <span>Subscription</span>
        </a>
        
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <span>LOGIN</span>
        </a>
        <a href="{% url 'accountapp:create' %}" class="pragmatic_header_nav">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
            <span>LOGOUT</span>
        </a>
        {% endif %}
    </div>

</div>